/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
 /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
 /*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
  SET NAMES utf8 ;
 /*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
 /*!40103 SET TIME_ZONE='+00:00' */;
 /*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
 /*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
 /*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
 /*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
 DROP TABLE IF EXISTS `amp$amps`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `amp$amps` (   `APID` bigint(18) unsigned NOT NULL COMMENT 'AMP Identifier',   `INVALID` tinyint(4) DEFAULT NULL COMMENT 'Invalidity flag',   `VPID` bigint(18) unsigned NOT NULL COMMENT 'VMP identifier',   `NM` varchar(255) NOT NULL COMMENT 'Actual Medicinal Product Name',   `ABBREVNM` varchar(60) DEFAULT NULL COMMENT 'Actual Medicinal Product Abbreviated name',   `DESC` text NOT NULL COMMENT 'Actual Medicinal Product Decription',   `NMDT` char(10) DEFAULT NULL COMMENT 'Date of name applicability',   `NM_PREV` varchar(255) DEFAULT NULL COMMENT 'Previous Name',   `SUPPCD` bigint(18) unsigned NOT NULL COMMENT 'Supplier',   `LIC_AUTHCD` smallint(4) unsigned zerofill NOT NULL COMMENT 'Current Licensing Authority',   `LIC_AUTH_PREVCD` smallint(4) unsigned zerofill DEFAULT NULL COMMENT 'Previous Licensing Authority Code',   `LIC_AUTHCHANGECD` smallint(4) unsigned zerofill DEFAULT NULL COMMENT 'Reason for change of licensing authority',   `LIC_AUTHCHANGEDT` char(10) DEFAULT NULL COMMENT 'Date of change of licensing authority',   `COMBPRODCD` smallint(4) unsigned zerofill DEFAULT NULL COMMENT 'Combination product indicator',   `FLAVOURCD` smallint(4) unsigned zerofill DEFAULT NULL COMMENT 'Flavour',   `EMA` tinyint(4) DEFAULT NULL COMMENT 'EMA Additional Monitoring indicator',   `PARALLEL_IMPORT` tinyint(4) DEFAULT NULL COMMENT 'Parallel Import indicator',   `AVAIL_RESTRICTCD` smallint(4) unsigned zerofill NOT NULL COMMENT 'Restrictions on availability',   PRIMARY KEY (`APID`),   UNIQUE KEY `APID_UNIQUE` (`APID`),   KEY `FK__amp$amps$vpid__vmp$vmps$vpid` (`VPID`),   KEY `LU__amp$amps$suppcd__supplier_idx` (`SUPPCD`),   KEY `LU__amp$amps$lic_auth_prevcd__licensing_authority_idx` (`LIC_AUTH_PREVCD`),   KEY `LU__amp$amps$lic_authchangecd_idx` (`LIC_AUTHCHANGECD`),   KEY `LU__amp$amps$combprodcd_idx` (`COMBPRODCD`),   KEY `LU__amp$amps$flavourcd__flavour_idx` (`FLAVOURCD`),   KEY `LU__amp$amps$avail_restrictcd__availability_restricton_idx` (`AVAIL_RESTRICTCD`),   KEY `LU__amp$amps$lic_authcd__licensing_authority` (`LIC_AUTHCD`),   CONSTRAINT `FK__amp$amps$vpid__vmp$vmps$vpid` FOREIGN KEY (`VPID`) REFERENCES `vmp$vmps` (`VPID`),   CONSTRAINT `LU__amp$amps$avail_restrictcd__availability_restricton` FOREIGN KEY (`AVAIL_RESTRICTCD`) REFERENCES `lookup$availability_restriction` (`CD`),   CONSTRAINT `LU__amp$amps$combprodcd` FOREIGN KEY (`COMBPRODCD`) REFERENCES `lookup$combination_prod_ind` (`CD`),   CONSTRAINT `LU__amp$amps$flavourcd__flavour` FOREIGN KEY (`FLAVOURCD`) REFERENCES `lookup$flavour` (`CD`),   CONSTRAINT `LU__amp$amps$lic_auth_prevcd__licensing_authority` FOREIGN KEY (`LIC_AUTH_PREVCD`) REFERENCES `lookup$licensing_authority` (`CD`),   CONSTRAINT `LU__amp$amps$lic_authcd__licensing_authority` FOREIGN KEY (`LIC_AUTHCD`) REFERENCES `lookup$licensing_authority` (`CD`),   CONSTRAINT `LU__amp$amps$lic_authchangecd` FOREIGN KEY (`LIC_AUTHCHANGECD`) REFERENCES `lookup$licensing_authority_change_reason` (`CD`),   CONSTRAINT `LU__amp$amps$suppcd__supplier` FOREIGN KEY (`SUPPCD`) REFERENCES `lookup$supplier` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Actual Medicinal Product';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `amp$ap_information`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `amp$ap_information` (   `APID` bigint(18) unsigned NOT NULL COMMENT 'AMP identifier',   `SZ_WEIGHT` varchar(100) DEFAULT NULL COMMENT 'Size / Weight',   `COLOURCD` smallint(4) unsigned zerofill DEFAULT NULL COMMENT 'Colour',   `PROD_ORDER_NO` varchar(20) DEFAULT NULL COMMENT 'Product order number',   KEY `FK__amp$ainfo$apid__amp$amps$apid_idx` (`APID`),   KEY `LU__amp$ainfo$colourcd__colour_idx` (`COLOURCD`),   CONSTRAINT `FK__amp$ainfo$apid__amp$amps$apid` FOREIGN KEY (`APID`) REFERENCES `amp$amps` (`APID`),   CONSTRAINT `LU__amp$ainfo$colourcd__colour` FOREIGN KEY (`COLOURCD`) REFERENCES `lookup$colour` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Appliance information';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `amp$ap_ingredient`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `amp$ap_ingredient` (   `APID` bigint(18) unsigned NOT NULL COMMENT 'AMP identifier',   `ISID` bigint(18) unsigned NOT NULL COMMENT 'Ingredient substance identifier',   `STRNTH` decimal(10,3) DEFAULT NULL COMMENT 'Pharmaceutical strength numerical value',   `UOMCD` bigint(18) unsigned DEFAULT NULL COMMENT 'Pharmaceutical Strength Unit of Measure',   KEY `FK__amp$aingr$apid__amp$amps$apid_idx` (`APID`),   KEY `FK__amp$aingr$isid__ingredient$is$isid_idx` (`ISID`),   KEY `LU__amp$aingr$uomcd__unit_of_measure_idx` (`UOMCD`),   CONSTRAINT `FK__amp$aingr$apid__amp$amps$apid` FOREIGN KEY (`APID`) REFERENCES `amp$amps` (`APID`),   CONSTRAINT `FK__amp$aingr$isid__ingredient$is$isid` FOREIGN KEY (`ISID`) REFERENCES `ingredient$ingredient_substances` (`ISID`),   CONSTRAINT `LU__amp$aingr$uomcd__unit_of_measure` FOREIGN KEY (`UOMCD`) REFERENCES `lookup$unit_of_measure` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Actual Product Excipients';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `amp$licensed_route`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `amp$licensed_route` (   `APID` bigint(18) unsigned NOT NULL COMMENT 'AMP identifier',   `ROUTECD` bigint(18) unsigned NOT NULL COMMENT 'Licenced route',   KEY `FK__amp$lr$apid__amp$amps$apid_idx` (`APID`),   KEY `LU__amp$lr$routecd__route_idx` (`ROUTECD`),   CONSTRAINT `FK__amp$lr$apid__amp$amps$apid` FOREIGN KEY (`APID`) REFERENCES `amp$amps` (`APID`),   CONSTRAINT `LU__amp$lr$routecd__route` FOREIGN KEY (`ROUTECD`) REFERENCES `lookup$route` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Licensed route';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `ampp$ampps`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `ampp$ampps` (   `APPID` bigint(18) unsigned DEFAULT NULL COMMENT 'AMPP identifier',   `INVALID` tinyint(4) DEFAULT NULL COMMENT 'Invalidity flag',   `NM` varchar(774) NOT NULL COMMENT 'Actual Medicinal Product Pack description',   `ABBREVNM` varchar(60) DEFAULT NULL COMMENT 'Actual Medicinal Product Pack Abbreviated Name',   `VPPID` bigint(18) unsigned NOT NULL COMMENT 'VMPP identifier',   `APID` bigint(18) unsigned NOT NULL COMMENT 'AMP identifier',   `COMBPACKCD` smallint(4) unsigned zerofill DEFAULT NULL COMMENT 'Combination pack',   `LEGAL_CATCD` smallint(4) unsigned zerofill NOT NULL COMMENT 'Legal category',   `SUBP` varchar(30) DEFAULT NULL COMMENT 'Sub Pack Info',   `DISCCD` smallint(4) unsigned zerofill DEFAULT NULL COMMENT 'Discontinued Flag',   `DISCDT` char(10) DEFAULT NULL COMMENT 'Discontinued Flag Change date',   UNIQUE KEY `APPID_UNIQUE` (`APPID`),   KEY `FK__ampp$ampps$vppid__vmpp$vmpps$vppid_idx` (`VPPID`),   KEY `FK__ampp$ampps$apid__amp$amps$apid_idx` (`APID`),   KEY `LU__ampp$ampps$combpackcd__combination_pack_ind_idx` (`COMBPACKCD`),   KEY `LU__ampp$ampps$legal_catcd__legal_category_idx` (`LEGAL_CATCD`),   KEY `LU__ampp$ampps$disccd__discontinued_ind_idx` (`DISCCD`),   CONSTRAINT `FK__ampp$ampps$apid__amp$amps$apid` FOREIGN KEY (`APID`) REFERENCES `amp$amps` (`APID`),   CONSTRAINT `FK__ampp$ampps$vppid__vmpp$vmpps$vppid` FOREIGN KEY (`VPPID`) REFERENCES `vmpp$vmpps` (`VPPID`),   CONSTRAINT `LU__ampp$ampps$combpackcd__combination_pack_ind` FOREIGN KEY (`COMBPACKCD`) REFERENCES `lookup$combination_pack_ind` (`CD`),   CONSTRAINT `LU__ampp$ampps$disccd__discontinued_ind` FOREIGN KEY (`DISCCD`) REFERENCES `lookup$discontinued_ind` (`CD`),   CONSTRAINT `LU__ampp$ampps$legal_catcd__legal_category` FOREIGN KEY (`LEGAL_CATCD`) REFERENCES `lookup$legal_category` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Actual Medicinal Product Packs';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `ampp$appliance_pack_info`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `ampp$appliance_pack_info` (   `APPID` bigint(18) unsigned NOT NULL COMMENT 'AMPP identifier',   `REIMB_STATCD` smallint(4) unsigned zerofill NOT NULL COMMENT 'Appliance Reimbursement status',   `REIMB_STATDT` char(10) DEFAULT NULL COMMENT 'Date of Appliance reimbursement status applicability',   `REIMB_STATPREVCD` smallint(4) unsigned zerofill DEFAULT NULL COMMENT 'Appliance Reimbursement previous status code',   `PACK_ORDER_NO` varchar(20) DEFAULT NULL COMMENT 'Pack order number',   KEY `LU__ampp$api$reimb_statcd__reimbursement_status_idx` (`REIMB_STATCD`),   KEY `FK__ampp$api$appid__ampp$ampps$appid_idx` (`APPID`),   KEY `LU__ampp$api$reimb_statprevcd__reimbursement_status_idx` (`REIMB_STATPREVCD`),   CONSTRAINT `FK__ampp$api$appid__ampp$ampps$appid` FOREIGN KEY (`APPID`) REFERENCES `ampp$ampps` (`APPID`),   CONSTRAINT `LU__ampp$api$reimb_statcd__reimbursement_status` FOREIGN KEY (`REIMB_STATCD`) REFERENCES `lookup$reimbursement_status` (`CD`),   CONSTRAINT `LU__ampp$api$reimb_statprevcd__reimbursement_status` FOREIGN KEY (`REIMB_STATPREVCD`) REFERENCES `lookup$reimbursement_status` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Appliance pack Information';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `ampp$comb_content`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `ampp$comb_content` (   `PRNTAPPID` bigint(18) unsigned NOT NULL COMMENT 'Parent pack AMPP identifier',   `CHLDAPPID` bigint(18) unsigned NOT NULL COMMENT 'Sub pack AMPP identifier',   KEY `FK__ampp$cc$prntappid__ampp$ampps$appid_idx` (`PRNTAPPID`),   KEY `FK__ampp$cc$chldappid__ampp$ampps$appid_idx` (`CHLDAPPID`),   CONSTRAINT `FK__ampp$cc$chldappid__ampp$ampps$appid` FOREIGN KEY (`CHLDAPPID`) REFERENCES `ampp$ampps` (`APPID`),   CONSTRAINT `FK__ampp$cc$prntappid__ampp$ampps$appid` FOREIGN KEY (`PRNTAPPID`) REFERENCES `ampp$ampps` (`APPID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Combination Pack content';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `ampp$drug_product_prescrib_info`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `ampp$drug_product_prescrib_info` (   `APPID` bigint(18) unsigned NOT NULL COMMENT 'AMPP identifier',   `SCHED_2` tinyint(4) DEFAULT NULL COMMENT 'Schedule 2 indicator',   `ACBS` tinyint(4) DEFAULT NULL COMMENT 'ACBS indicator',   `PADM` tinyint(4) DEFAULT NULL COMMENT 'Personally Administered indicator',   `FP10_MDA` tinyint(4) DEFAULT NULL COMMENT 'FP10 MDA Prescription indicator',   `SCHED_1` tinyint(4) DEFAULT NULL COMMENT 'Schedule 1 indicator',   `HOSP` tinyint(4) DEFAULT NULL COMMENT 'Hospital indicator',   `NURSE_F` tinyint(4) DEFAULT NULL COMMENT 'Nurse Formulary indicator',   `ENURSE_F` tinyint(4) DEFAULT NULL COMMENT 'Nurse Extended Formulary indicator',   `DENT_F` tinyint(4) DEFAULT NULL COMMENT 'Dental Formulary indicator',   KEY `FK__ampp$dppi$appid__ampp$ampps$appid_idx` (`APPID`),   CONSTRAINT `FK__ampp$dppi$appid__ampp$ampps$appid` FOREIGN KEY (`APPID`) REFERENCES `ampp$ampps` (`APPID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Product Prescribing Information';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `ampp$medicinal_product_price`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `ampp$medicinal_product_price` (   `APPID` bigint(18) unsigned NOT NULL COMMENT 'AMPP identifier',   `PRICE` int(9) DEFAULT NULL COMMENT 'Price',   `PRICEDT` char(10) DEFAULT NULL COMMENT 'Date of price validity',   `PRICE_PREV` int(9) DEFAULT NULL COMMENT 'Price prior to change date',   `PRICE_BASISCD` smallint(4) unsigned zerofill NOT NULL COMMENT 'Price basis',   KEY `FK__ampp$mpp$appid__ampp$ampps$appid_idx` (`APPID`),   KEY `LU__ampp$mpp$price_basiscd__price_basis_idx` (`PRICE_BASISCD`),   CONSTRAINT `FK__ampp$mpp$appid__ampp$ampps$appid` FOREIGN KEY (`APPID`) REFERENCES `ampp$ampps` (`APPID`),   CONSTRAINT `LU__ampp$mpp$price_basiscd__price_basis` FOREIGN KEY (`PRICE_BASISCD`) REFERENCES `lookup$price_basis` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Medicinal product price';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `ampp$reimbursement_info`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `ampp$reimbursement_info` (   `APPID` bigint(18) unsigned NOT NULL COMMENT 'AMPP identifier',   `PX_CHRGS` tinyint(2) DEFAULT NULL COMMENT 'Prescription Charges',   `DISP_FEES` tinyint(2) DEFAULT NULL COMMENT 'Dispensing Fees',   `BB` tinyint(4) DEFAULT NULL COMMENT 'Broken Bulk indicator',   `LTD_STAB` varchar(45) DEFAULT NULL,   `CAL_PACK` tinyint(4) DEFAULT NULL COMMENT 'Calendar pack indicator',   `SPEC_CONTCD` smallint(4) unsigned zerofill DEFAULT NULL COMMENT 'Special Container Indicator',   `DND` smallint(4) unsigned zerofill DEFAULT NULL COMMENT 'Discount Not Deducted Indicator',   `FP34D` tinyint(4) DEFAULT NULL COMMENT 'FP34D prescription item indicator',   KEY `FK__ampp$ri$appid__ampp$ampps$appid_idx` (`APPID`),   KEY `LU__ampp$ri$spec_contcd__spec_cont_idx` (`SPEC_CONTCD`),   CONSTRAINT `FK__ampp$ri$appid__ampp$ampps$appid` FOREIGN KEY (`APPID`) REFERENCES `ampp$ampps` (`APPID`),   CONSTRAINT `LU__ampp$ri$spec_contcd__spec_cont` FOREIGN KEY (`SPEC_CONTCD`) REFERENCES `lookup$spec_cont` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AMPP reimbursement information';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `ingredient$ingredient_substances`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `ingredient$ingredient_substances` (   `ISID` bigint(18) unsigned NOT NULL COMMENT 'Ingredient Substance Identifier',   `ISIDDT` char(10) DEFAULT NULL COMMENT 'Date Ingredient substance identifier became valid',   `ISIDPREV` bigint(18) unsigned DEFAULT NULL COMMENT 'Previous Ingredient substance identifier',   `INVALID` tinyint(4) DEFAULT NULL COMMENT 'Invalidity flag',   `NM` varchar(255) NOT NULL COMMENT 'Ingredient Substance Name',   PRIMARY KEY (`ISID`),   UNIQUE KEY `ISID_UNIQUE` (`ISID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Ingredients';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `lookup$availability_restriction`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `lookup$availability_restriction` (   `CD` smallint(4) unsigned zerofill NOT NULL,   `DESC` varchar(60) NOT NULL,   PRIMARY KEY (`CD`),   UNIQUE KEY `CD_UNIQUE` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AMP availability restriction';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `lookup$basis_of_name`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `lookup$basis_of_name` (   `CD` smallint(4) unsigned zerofill NOT NULL,   `DESC` varchar(150) NOT NULL,   PRIMARY KEY (`CD`),   UNIQUE KEY `CD_UNIQUE` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='VMP name basis';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `lookup$basis_of_strnth`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `lookup$basis_of_strnth` (   `CD` smallint(4) unsigned zerofill NOT NULL,   `DESC` varchar(150) NOT NULL,   PRIMARY KEY (`CD`),   UNIQUE KEY `CD_UNIQUE` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Basis of strength';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `lookup$colour`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `lookup$colour` (   `CD` smallint(4) unsigned zerofill NOT NULL,   `DESC` varchar(60) NOT NULL,   PRIMARY KEY (`CD`),   UNIQUE KEY `CD_UNIQUE` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Colours';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `lookup$combination_pack_ind`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `lookup$combination_pack_ind` (   `CD` smallint(4) unsigned zerofill NOT NULL,   `DESC` varchar(60) NOT NULL,   PRIMARY KEY (`CD`),   UNIQUE KEY `CD_UNIQUE` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AMPP/VMPP combination indicator';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `lookup$combination_prod_ind`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `lookup$combination_prod_ind` (   `CD` smallint(4) unsigned zerofill NOT NULL,   `DESC` varchar(60) NOT NULL,   PRIMARY KEY (`CD`),   UNIQUE KEY `CD_UNIQUE` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AMP/VMP combination indicator';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `lookup$control_drug_category`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `lookup$control_drug_category` (   `CD` smallint(4) unsigned zerofill NOT NULL,   `DESC` varchar(60) NOT NULL,   PRIMARY KEY (`CD`),   UNIQUE KEY `CD_UNIQUE` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Controlled drug category';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `lookup$df_indicator`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `lookup$df_indicator` (   `CD` tinyint(1) unsigned zerofill NOT NULL,   `DESC` varchar(20) NOT NULL,   PRIMARY KEY (`CD`),   UNIQUE KEY `CD_UNIQUE` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Dose form indicator';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `lookup$discontinued_ind`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `lookup$discontinued_ind` (   `CD` smallint(4) unsigned zerofill NOT NULL,   `DESC` varchar(60) NOT NULL,   PRIMARY KEY (`CD`),   UNIQUE KEY `CD_UNIQUE` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Discontinued indicator';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `lookup$dnd`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `lookup$dnd` (   `CD` smallint(4) unsigned zerofill NOT NULL,   `DESC` varchar(60) NOT NULL,   PRIMARY KEY (`CD`),   UNIQUE KEY `CD_UNIQUE` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Discount Not Deducted indicator';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `lookup$dt_payment_category`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `lookup$dt_payment_category` (   `CD` smallint(4) unsigned zerofill NOT NULL,   `DESC` varchar(60) NOT NULL,   PRIMARY KEY (`CD`),   UNIQUE KEY `CD_UNIQUE` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Drug Tariff categories';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `lookup$flavour`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `lookup$flavour` (   `CD` smallint(4) unsigned zerofill NOT NULL,   `DESC` varchar(60) NOT NULL,   PRIMARY KEY (`CD`),   UNIQUE KEY `CD_UNIQUE` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Flvours';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `lookup$form`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `lookup$form` (   `CD` bigint(18) unsigned NOT NULL,   `CDDT` char(10) DEFAULT NULL,   `CDPREV` bigint(18) unsigned DEFAULT NULL,   `DESC` varchar(60) NOT NULL,   PRIMARY KEY (`CD`),   UNIQUE KEY `CD_UNIQUE` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Formulations';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `lookup$legal_category`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `lookup$legal_category` (   `CD` smallint(4) unsigned zerofill NOT NULL,   `DESC` varchar(60) NOT NULL,   PRIMARY KEY (`CD`),   UNIQUE KEY `CD_UNIQUE` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AMPP legal category';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `lookup$licensing_authority`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `lookup$licensing_authority` (   `CD` smallint(4) unsigned zerofill NOT NULL,   `DESC` varchar(60) NOT NULL,   PRIMARY KEY (`CD`),   UNIQUE KEY `CD_UNIQUE` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Licensing authority';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `lookup$licensing_authority_change_reason`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `lookup$licensing_authority_change_reason` (   `CD` smallint(4) unsigned zerofill NOT NULL,   `DESC` varchar(60) NOT NULL,   PRIMARY KEY (`CD`),   UNIQUE KEY `CD_UNIQUE` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Licensing authority change reason';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `lookup$namechange_reason`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `lookup$namechange_reason` (   `CD` smallint(4) unsigned zerofill NOT NULL,   `DESC` varchar(150) NOT NULL,   PRIMARY KEY (`CD`),   UNIQUE KEY `CD_UNIQUE` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='VMP name change reason';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `lookup$ont_form_route`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `lookup$ont_form_route` (   `CD` smallint(4) unsigned zerofill NOT NULL,   `DESC` varchar(60) NOT NULL,   PRIMARY KEY (`CD`),   UNIQUE KEY `CD_UNIQUE` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Ontology form route combinations';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `lookup$price_basis`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `lookup$price_basis` (   `CD` smallint(4) unsigned zerofill NOT NULL,   `DESC` varchar(60) NOT NULL,   PRIMARY KEY (`CD`),   UNIQUE KEY `CD_UNIQUE` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Basis of AMPP price';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `lookup$reimbursement_status`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `lookup$reimbursement_status` (   `CD` smallint(4) unsigned zerofill NOT NULL,   `DESC` varchar(60) NOT NULL,   PRIMARY KEY (`CD`),   UNIQUE KEY `CD_UNIQUE` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Reimbursement status';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `lookup$route`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `lookup$route` (   `CD` bigint(18) unsigned NOT NULL,   `CDDT` char(10) DEFAULT NULL,   `CDPREV` bigint(18) unsigned DEFAULT NULL,   `DESC` varchar(60) NOT NULL,   PRIMARY KEY (`CD`),   UNIQUE KEY `CD_UNIQUE` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Routes of administration';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `lookup$spec_cont`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `lookup$spec_cont` (   `CD` smallint(4) unsigned zerofill NOT NULL,   `DESC` varchar(60) NOT NULL,   PRIMARY KEY (`CD`),   UNIQUE KEY `CD_UNIQUE` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Special container indicator';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `lookup$supplier`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `lookup$supplier` (   `CD` bigint(18) unsigned NOT NULL,   `CDDT` char(10) DEFAULT NULL,   `CDPREV` bigint(18) unsigned DEFAULT NULL,   `INVALID` tinyint(4) DEFAULT NULL,   `DESC` varchar(80) NOT NULL,   PRIMARY KEY (`CD`),   UNIQUE KEY `CD_UNIQUE` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Suppliers';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `lookup$unit_of_measure`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `lookup$unit_of_measure` (   `CD` bigint(18) unsigned NOT NULL,   `CDDT` char(10) DEFAULT NULL,   `CDPREV` bigint(18) unsigned DEFAULT NULL,   `DESC` varchar(150) NOT NULL,   PRIMARY KEY (`CD`),   UNIQUE KEY `CD_UNIQUE` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Units of measure';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `lookup$virtual_product_non_avail`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `lookup$virtual_product_non_avail` (   `CD` smallint(4) unsigned zerofill NOT NULL,   `DESC` varchar(60) NOT NULL,   PRIMARY KEY (`CD`),   UNIQUE KEY `CD_UNIQUE` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='VMP non availability';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `lookup$virtual_product_pres_status`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `lookup$virtual_product_pres_status` (   `CD` smallint(4) unsigned zerofill NOT NULL,   `DESC` varchar(60) NOT NULL,   PRIMARY KEY (`CD`),   UNIQUE KEY `CD_UNIQUE` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='VMP prescribing status';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `vmp$control_drug_info`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `vmp$control_drug_info` (   `VPID` bigint(18) unsigned NOT NULL COMMENT 'VMP identifier',   `CATCD` smallint(4) unsigned zerofill NOT NULL COMMENT 'Control Drug category',   `CATDT` char(10) DEFAULT NULL COMMENT 'Date of applicability',   `CAT_PREVCD` smallint(4) unsigned zerofill DEFAULT NULL COMMENT 'Previous Control Drug Information',   KEY `FK__vmp$cdi$vpid__vmp$vmps$vpid` (`VPID`),   KEY `LU__vmp$cdi$catcd__control_drug_category_idx` (`CATCD`),   KEY `LU__vmp$cdi$cat_prevcd__control_drug_category_idx` (`CAT_PREVCD`),   CONSTRAINT `FK__vmp$cdi$vpid__vmp$vmps$vpid` FOREIGN KEY (`VPID`) REFERENCES `vmp$vmps` (`VPID`),   CONSTRAINT `LU__vmp$cdi$cat_prevcd__control_drug_category` FOREIGN KEY (`CAT_PREVCD`) REFERENCES `lookup$control_drug_category` (`CD`),   CONSTRAINT `LU__vmp$cdi$catcd__control_drug_category` FOREIGN KEY (`CATCD`) REFERENCES `lookup$control_drug_category` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Control Drug Info';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `vmp$drug_form`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `vmp$drug_form` (   `VPID` bigint(18) unsigned NOT NULL,   `FORMCD` bigint(18) unsigned NOT NULL,   KEY `LU__vmp$df$formcd__form_idx` (`FORMCD`),   KEY `FK__vmp$df$vpid__vmp$vmps$vpid` (`VPID`),   CONSTRAINT `FK__vmp$df$vpid__vmp$vmps$vpid` FOREIGN KEY (`VPID`) REFERENCES `vmp$vmps` (`VPID`),   CONSTRAINT `LU__vmp$df$formcd__form` FOREIGN KEY (`FORMCD`) REFERENCES `lookup$form` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Drug Form';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `vmp$drug_route`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `vmp$drug_route` (   `VPID` bigint(18) unsigned NOT NULL COMMENT 'VMP identifier',   `ROUTECD` bigint(18) unsigned NOT NULL COMMENT 'Route',   KEY `FK__vmp$dr$vpid__vmp$vmps$vpid` (`VPID`),   KEY `LU__vmp$dr$routecd__route_idx` (`ROUTECD`),   CONSTRAINT `FK__vmp$dr$vpid__vmp$vmps$vpid` FOREIGN KEY (`VPID`) REFERENCES `vmp$vmps` (`VPID`),   CONSTRAINT `LU__vmp$dr$routecd__route` FOREIGN KEY (`ROUTECD`) REFERENCES `lookup$route` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Drug Route';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `vmp$ont_drug_form`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `vmp$ont_drug_form` (   `VPID` bigint(18) unsigned NOT NULL COMMENT 'VMP ID',   `FORMCD` smallint(4) unsigned zerofill NOT NULL COMMENT 'Virtual Medicinal Product Form & Route',   KEY `FK__vmp$odf$vpid__vmp$vmps$vpid` (`VPID`),   KEY `LU__vmp$odf$formcd__ont_form_route_idx` (`FORMCD`),   CONSTRAINT `FK__vmp$odf$vpid__vmp$vmps$vpid` FOREIGN KEY (`VPID`) REFERENCES `vmp$vmps` (`VPID`),   CONSTRAINT `LU__vmp$odf$formcd__ont_form_route` FOREIGN KEY (`FORMCD`) REFERENCES `lookup$ont_form_route` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Ontology Form & Route Information';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `vmp$virtual_product_ingredient`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `vmp$virtual_product_ingredient` (   `VPID` bigint(18) unsigned NOT NULL COMMENT 'VMP identifier',   `ISID` bigint(18) unsigned NOT NULL COMMENT 'Ingredient substance identifier',   `BASIS_STRNTCD` smallint(4) unsigned zerofill DEFAULT NULL COMMENT 'Basis of pharmaceutical strength',   `BS_SUBID` bigint(18) unsigned DEFAULT NULL COMMENT 'Basis of strength substance identifier',   `STRNT_NMRTR_VAL` decimal(10,3) DEFAULT NULL COMMENT 'Strength value numerator',   `STRNT_NMRTR_UOMCD` bigint(18) unsigned DEFAULT NULL COMMENT 'Strength value numerator unit',   `STRNT_DNMTR_VAL` decimal(10,3) DEFAULT NULL COMMENT 'Strength value denominator',   `STRNT_DNMTR_UOMCD` bigint(18) unsigned DEFAULT NULL COMMENT 'Strength value denominator unit',   KEY `FK__vmp$vpi$vpid__vmp$vmps$vpid` (`VPID`) /*!80000 INVISIBLE */,   KEY `LU__vmp$vpi$basis_strntcd__basis_of_name_idx` (`BASIS_STRNTCD`),   KEY `FK__vmp$vpi$bs_subid__ingredient$ingredient_substances$isid_idx` (`BS_SUBID`),   KEY `FK__vmp$vpi$isid__ingredient$ingredient_substances$isid_idx` (`ISID`),   KEY `LU__vmp$vpi$strnt_nmrtr_uomcd__unit_of_measure_idx` (`STRNT_NMRTR_UOMCD`),   KEY `LU__vmp$vpi$strnt_dmrtr_uomcd__unit_of_measure_idx` (`STRNT_DNMTR_UOMCD`),   CONSTRAINT `FK__vmp$vpi$bs_subid__ingredient$is$isid` FOREIGN KEY (`BS_SUBID`) REFERENCES `ingredient$ingredient_substances` (`ISID`),   CONSTRAINT `FK__vmp$vpi$isid__ingredient$is$isid` FOREIGN KEY (`ISID`) REFERENCES `ingredient$ingredient_substances` (`ISID`),   CONSTRAINT `FK__vmp$vpi$vpid__vmp$vmps$vpid` FOREIGN KEY (`VPID`) REFERENCES `vmp$vmps` (`VPID`),   CONSTRAINT `LU__vmp$vpi$basis_strntcd__basis_of_name` FOREIGN KEY (`BASIS_STRNTCD`) REFERENCES `lookup$basis_of_name` (`CD`),   CONSTRAINT `LU__vmp$vpi$strnt_dmrtr_uomcd__unit_of_measure` FOREIGN KEY (`STRNT_DNMTR_UOMCD`) REFERENCES `lookup$unit_of_measure` (`CD`),   CONSTRAINT `LU__vmp$vpi$strnt_nmrtr_uomcd__unit_of_measure` FOREIGN KEY (`STRNT_NMRTR_UOMCD`) REFERENCES `lookup$unit_of_measure` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Virtual Product Ingredient';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `vmp$vmps`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `vmp$vmps` (   `VPID` bigint(18) unsigned NOT NULL COMMENT 'Virtual Medicinal Product identifier',   `VPIDDT` char(10) DEFAULT NULL COMMENT 'Date VMP identifier became valid',   `VPIDPREV` bigint(18) unsigned DEFAULT NULL COMMENT 'Previous product identifier',   `VTMID` bigint(18) unsigned DEFAULT NULL COMMENT 'VTM identifier',   `INVALID` tinyint(4) DEFAULT NULL COMMENT 'Invalidity flag',   `NM` varchar(255) NOT NULL COMMENT 'Virtual Medicinal Product Name',   `ABBREVNM` varchar(60) DEFAULT NULL COMMENT 'Virtual Medicinal Product Abbreviated name',   `BASISCD` smallint(4) unsigned zerofill NOT NULL COMMENT 'Basis of preferred name',   `NMDT` char(10) DEFAULT NULL COMMENT 'Date of Name applicability',   `NMPREV` varchar(255) DEFAULT NULL COMMENT 'Previous Name',   `BASIS_PREVCD` smallint(4) unsigned zerofill DEFAULT NULL COMMENT 'Basis of previous name',   `NMCHANGECD` smallint(4) unsigned zerofill DEFAULT NULL COMMENT 'Reason for name change',   `COMBPRODCD` smallint(4) unsigned zerofill DEFAULT NULL COMMENT 'Combination product Indicator',   `PRES_STATCD` smallint(4) unsigned zerofill NOT NULL COMMENT 'Virtual Medicinal Product Prescribing Status',   `SUG_F` tinyint(4) DEFAULT NULL COMMENT 'Sugar Free Indicator',   `GLU_F` tinyint(4) DEFAULT NULL COMMENT 'Gluten Free Indicator',   `PRES_F` tinyint(4) DEFAULT NULL COMMENT 'Preservative Free Indicator',   `CFC_F` tinyint(4) DEFAULT NULL COMMENT 'CFC Free Indicator',   `NON_AVAILCD` smallint(4) unsigned zerofill DEFAULT NULL COMMENT 'Non-availability indicator',   `NON_AVAILDT` char(10) DEFAULT NULL COMMENT 'Non availability status date',   `DF_INDCD` tinyint(1) unsigned zerofill DEFAULT NULL COMMENT 'Dose form indicator',   `UDFS` decimal(10,3) DEFAULT NULL COMMENT 'Unit dose form size',   `UDFS_UOMCD` bigint(18) unsigned DEFAULT NULL COMMENT 'Unit dose form units',   `UNIT_DOSE_UOMCD` bigint(18) unsigned DEFAULT NULL COMMENT 'Unit dose unit of measure',   PRIMARY KEY (`VPID`),   UNIQUE KEY `VPID_UNIQUE` (`VPID`),   KEY `FK__vmp$vmps$vtmid__vtm$virtual_therapeutic_moieties$vtmid_idx` (`VTMID`) /*!80000 INVISIBLE */,   KEY `LU__vmp$vmps$basiscd__basis_of_name_idx` (`BASISCD`),   KEY `LU__vmp$vmps$basis_prevcd__basis_of_name_idx` (`BASIS_PREVCD`),   KEY `LU__vmp$vmps$nmchangecd__namechange_reason_idx` (`NMCHANGECD`),   KEY `LU__vmp$vmps$combprodcd__combinaton_prod_ind_idx` (`COMBPRODCD`),   KEY `LU__vmp$vmps$pres_statcd__virtual_product_pres_status_idx` (`PRES_STATCD`),   KEY `LU__vmp$vmps$non_availcd__virtual_product_non_avail_idx` (`NON_AVAILCD`),   KEY `LU__vmp$vmps$df_indcd__df_indicator_idx` (`DF_INDCD`),   KEY `LU__vmp$vmps$udfs_uomcd__unit_of_measure_idx` (`UDFS_UOMCD`),   KEY `LU__vmp$vmps$unit_dose_uomcd__unit_of_measure_idx` (`UNIT_DOSE_UOMCD`) /*!80000 INVISIBLE */,   CONSTRAINT `FK__vmp$vmps$vtmid__vtm$virtual_therapeutic_moieties$vtmid` FOREIGN KEY (`VTMID`) REFERENCES `vtm$virtual_therapeutic_moieties` (`VTMID`),   CONSTRAINT `LU__vmp$vmps$basis_prevcd__basis_of_name` FOREIGN KEY (`BASIS_PREVCD`) REFERENCES `lookup$basis_of_name` (`CD`),   CONSTRAINT `LU__vmp$vmps$basiscd__basis_of_name` FOREIGN KEY (`BASISCD`) REFERENCES `lookup$basis_of_name` (`CD`),   CONSTRAINT `LU__vmp$vmps$combprodcd__combinaton_prod_ind` FOREIGN KEY (`COMBPRODCD`) REFERENCES `lookup$combination_prod_ind` (`CD`),   CONSTRAINT `LU__vmp$vmps$df_indcd__df_indicator` FOREIGN KEY (`DF_INDCD`) REFERENCES `lookup$df_indicator` (`CD`),   CONSTRAINT `LU__vmp$vmps$nmchangecd__namechange_reason` FOREIGN KEY (`NMCHANGECD`) REFERENCES `lookup$namechange_reason` (`CD`),   CONSTRAINT `LU__vmp$vmps$non_availcd__virtual_product_non_avail` FOREIGN KEY (`NON_AVAILCD`) REFERENCES `lookup$virtual_product_non_avail` (`CD`),   CONSTRAINT `LU__vmp$vmps$pres_statcd__virtual_product_pres_status` FOREIGN KEY (`PRES_STATCD`) REFERENCES `lookup$virtual_product_pres_status` (`CD`),   CONSTRAINT `LU__vmp$vmps$udfs_uomcd__unit_of_measure` FOREIGN KEY (`UDFS_UOMCD`) REFERENCES `lookup$unit_of_measure` (`CD`),   CONSTRAINT `LU__vmp$vmps$unit_dose_uomcd__unit_of_measure` FOREIGN KEY (`UNIT_DOSE_UOMCD`) REFERENCES `lookup$unit_of_measure` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `vmpp$comb_content`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `vmpp$comb_content` (   `PRNTVPPID` bigint(18) unsigned NOT NULL COMMENT 'Parent pack VMPP identifier',   `CHLDVPPID` bigint(18) unsigned NOT NULL COMMENT 'Sub pack VMPP identifier',   KEY `FK__vmpp$cc$prntvppid__vmpp$vmpps$vppid_idx` (`PRNTVPPID`),   KEY `FK__vmpp$cc$chldvppid__vmpp$vmpps$vppid_idx` (`CHLDVPPID`),   CONSTRAINT `FK__vmpp$cc$chldvppid__vmpp$vmpps$vppid` FOREIGN KEY (`CHLDVPPID`) REFERENCES `vmpp$vmpps` (`VPPID`),   CONSTRAINT `FK__vmpp$cc$prntvppid__vmpp$vmpps$vppid` FOREIGN KEY (`PRNTVPPID`) REFERENCES `vmpp$vmpps` (`VPPID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Combination Pack content';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `vmpp$drug_tariff_info`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `vmpp$drug_tariff_info` (   `VPPID` bigint(18) unsigned NOT NULL COMMENT 'VMPP identifier',   `PAY_CATCD` smallint(4) unsigned zerofill NOT NULL COMMENT 'Drug Tariff payment category',   `PRICE` int(6) DEFAULT NULL COMMENT 'Drug Tariff Price',   `DT` char(10) DEFAULT NULL COMMENT 'Date of DT price applicability',   `PREVPRICE` int(6) DEFAULT NULL COMMENT 'Previous price',   KEY `FK__vmpp$dti$vppid__vmpp$vmpps$vppid_idx` (`VPPID`),   KEY `LU__vmpp$dti$pay_catcd__dt_payment_category_idx` (`PAY_CATCD`),   CONSTRAINT `FK__vmpp$dti$vppid__vmpp$vmpps$vppid` FOREIGN KEY (`VPPID`) REFERENCES `vmpp$vmpps` (`VPPID`),   CONSTRAINT `LU__vmpp$dti$pay_catcd__dt_payment_category` FOREIGN KEY (`PAY_CATCD`) REFERENCES `lookup$dt_payment_category` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Drug Tariff Category Information';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `vmpp$vmpps`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `vmpp$vmpps` (   `VPPID` bigint(18) unsigned NOT NULL COMMENT 'Virtual Medicinal Product Pack Identifier',   `INVALID` tinyint(4) DEFAULT NULL COMMENT 'Invalidity flag',   `NM` varchar(420) NOT NULL COMMENT 'Virtual medicinal product pack description',   `VPID` bigint(18) unsigned NOT NULL COMMENT 'VMP identifier',   `QTYVAL` decimal(10,2) DEFAULT NULL COMMENT 'Quantity Value',   `QTY_UOMCD` bigint(18) unsigned DEFAULT NULL COMMENT 'Quantity Unit of Measure',   `COMBPACKCD` smallint(4) unsigned zerofill DEFAULT NULL COMMENT 'Combination pack indicator',   PRIMARY KEY (`VPPID`),   UNIQUE KEY `VPPID_UNIQUE` (`VPPID`),   KEY `FK__vmpp$vmpps$vpid__vmp$vmps_vpid` (`VPID`),   KEY `LU__vmpp$vmpps$qty_uomcd__unit_of_measure_idx` (`QTY_UOMCD`),   KEY `LU__vmpp$vmpps$combpackcd__combination_pack_ind_idx` (`COMBPACKCD`),   CONSTRAINT `FK__vmpp$vmpps$vpid__vmp$vmps_vpid` FOREIGN KEY (`VPID`) REFERENCES `vmp$vmps` (`VPID`),   CONSTRAINT `LU__vmpp$vmpps$combpackcd__combination_pack_ind` FOREIGN KEY (`COMBPACKCD`) REFERENCES `lookup$combination_pack_ind` (`CD`),   CONSTRAINT `LU__vmpp$vmpps$qty_uomcd__unit_of_measure` FOREIGN KEY (`QTY_UOMCD`) REFERENCES `lookup$unit_of_measure` (`CD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Virtual Medicinal Product Packs';
 /*!40101 SET character_set_client = @saved_cs_client */;
 DROP TABLE IF EXISTS `vtm$virtual_therapeutic_moieties`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
  SET character_set_client = utf8mb4 ;
 CREATE TABLE `vtm$virtual_therapeutic_moieties` (   `VTMID` bigint(18) unsigned NOT NULL COMMENT 'Virtual Therapeutic Moiety identifier',   `INVALID` tinyint(4) DEFAULT NULL COMMENT 'Invalidity flag',   `NM` varchar(255) NOT NULL COMMENT 'Virtual Therapeutic Moiety Name',   `ABBREVNM` varchar(60) DEFAULT NULL COMMENT 'Virtual Therapeutic Moiety Abbreviated name',   `VTMIDPREV` bigint(18) unsigned DEFAULT NULL COMMENT 'Previous VTM identifier',   `VTMIDDT` char(10) DEFAULT NULL COMMENT 'Virtual Therapeutic Moiety Identifier date',   PRIMARY KEY (`VTMID`),   UNIQUE KEY `VTMID_UNIQUE` (`VTMID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
 /*!40101 SET character_set_client = @saved_cs_client */;
 /*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;
 /*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
 /*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
 /*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
 /*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
 /*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
 /*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
 /*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
